// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDakSrpKgbpwP64ZbRx-oAb5_iOmhSSdTM',
    appId: '1:43533081267:web:75048d1ba359147fc6eec6',
    messagingSenderId: '43533081267',
    projectId: 'rebu-fletes',
    authDomain: 'rebu-fletes.firebaseapp.com',
    storageBucket: 'rebu-fletes.firebasestorage.app',
    measurementId: 'G-7K6CMBGM8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrsJdJUt36QtZDX45CCHCPDe8Jj_pF7e0',
    appId: '1:43533081267:android:ea95575f3cae7e22c6eec6',
    messagingSenderId: '43533081267',
    projectId: 'rebu-fletes',
    storageBucket: 'rebu-fletes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSd38iJfXpvPbUHYK-fUt0THfcsD7OV84',
    appId: '1:43533081267:ios:ca9f4850432d67bcc6eec6',
    messagingSenderId: '43533081267',
    projectId: 'rebu-fletes',
    storageBucket: 'rebu-fletes.firebasestorage.app',
    iosBundleId: 'com.example.rebuClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSd38iJfXpvPbUHYK-fUt0THfcsD7OV84',
    appId: '1:43533081267:ios:ca9f4850432d67bcc6eec6',
    messagingSenderId: '43533081267',
    projectId: 'rebu-fletes',
    storageBucket: 'rebu-fletes.firebasestorage.app',
    iosBundleId: 'com.example.rebuClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDakSrpKgbpwP64ZbRx-oAb5_iOmhSSdTM',
    appId: '1:43533081267:web:054aa92d15c54b89c6eec6',
    messagingSenderId: '43533081267',
    projectId: 'rebu-fletes',
    authDomain: 'rebu-fletes.firebaseapp.com',
    storageBucket: 'rebu-fletes.firebasestorage.app',
    measurementId: 'G-Q4DLNCNYGX',
  );

}